const actionTypes = {
    PRODUCT_LIST_REQUEST_IN_PROGRESS: 'PRODUCT_LIST_REQUEST_IN_PROGRESS',
    PRODUCT_LIST_REQUEST_SUCCESS: 'PRODUCT_LIST_REQUEST_SUCCESS',
    PRODUCT_LIST_REQUEST_FAILURE: 'PRODUCT_LIST_REQUEST_FAILURE'
};

export default actionTypes;